### ISSUE TITLE
X-Code installation check is skipped always.

### ISSUE THREAD

**Issue by PRi99** [kiriaze/mac-dev-env#2]
First of all, thank you for such an amazing script. :+1:

I have a minor problem, not sure if something is wrong from my end. The condition that checks for x-code existing installation is never met to true. Always the if condition block gets skipped and xcode installation command does not execute.

P.S.
I am new to shell scripting on os-x.

@dcondrey @kiriaze 
```
# xcode dev tools
  pretty_print "Installing xcode dev tools..."
  if [  "$(checkFor pkgutil --pkg-info=com.apple.pkg.CLTools_Executables)" ]; then
    printf 'Command-Line Tools is not installed.  Installing..' ;
    xcode-select --install
    sleep 1
    osascript -e 'tell application "System Events"' -e 'tell process "Install Command Line Developer Tools"' -e 'keystroke return' -e 'click button "Agree" of window "License Agreement"' -e 'end tell' -e 'end tell'
  fi
```

**Comment by kiriaze** [comment]
Hey @PRi99 thanks for the kind words!

Hmmm do you get a response after it prints out "Installing xcode dev tools..." or does it fail silently?

**Comment by PRi99** [comment]
The code inside If block does not enter or execute. I tried on two machines, one with Xcode already installed and one without.  Same behavior. 

Things work fine if i remove the If condition altogether,,  but when xcode is already installed,  prints unnecessary error saying tools available already.

**Comment by kiriaze** [comment]
Hmm @PRi99 Sorry its taken so long to get back to, but I've tried it a couple times on my MBP 11' Yosemite, but no hiccups encountered..ill see if I can find a friend with a different machine to try as well - but for now closing this as I've yet to encounter it.
